#!/usr/bin/env bash
# This script that gives you information about the school file.

file="school"

if [ ! -e $file ];
then
	echo "$file school file does not exist"
else
	echo "$file school file exists"

	if [ ! -s $file ];
	then
		echo "$file school file is empty"
	else
		echo "$file school file is not empty"
	fi

	if [ -f $file ];
	then
		echo "school is a regular file"
	fi
fi